openapi: 3.0.0
info:
  version: 1.0.0
  title: My docs
servers:
  - url: http://localhost:8000
    description: Local server
paths:
  /tasks:
    get:
      description: List all tasks
      responses:
        200:
          description: Returns all tasks.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/Task'
                  total:
                    type: integer
                    example: 1
                  page:
                    type: integer
                    example: 1
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Internal server error

    post:
      description: Create new task
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        201:
          description: Returns a new task created.
          content:
              application/json:
                schema:
                  type: object
                  properties:
                      data:
                        $ref: '#/components/schemas/Task'
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'

  /tasks/{id}:
    get:
      description: Get task by id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Returns a task by id.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/Task'
        404:
          description: Task not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Task not found
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'

    put:
      description: Update task by id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        200:
          description: Returns a task updated.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/Task'
        404:
          description: Task not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Task not found
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'

    delete:
      description: Delete task by id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        204:
          description: Task deleted
        404:
          description: Task not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Task not found
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'


components:
  schemas:
    Task:
      type: object
      required:
        - title
        - description
      properties:
        id:
          type: string
          readOnly: true
        title:
          type: string
        description:
          type: string
        createdAt:
            type: string
            format: date-time
            readOnly: true
        updatedAt:
            type: string
            format: date-time
            readOnly: true

    InternalServerError:
      type: object
      properties:
        message:
          type: string
          readOnly: true
          example: Internal server error
